eureka:
  instance:
    hostname: Activity_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka


spring:
  application:
     name: Activity_Service

  security:
    user:
      name: mabrouka
      password: annabi
  datasource:
    url: jdbc:postgresql://postgres:5432/activitydb
    username: postgres
    password: insy2s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  management:
    endpoints:
    web:
      exposure:
        include: "*"
        spring:
          config:
             import: optional:configserver:http://config-server:8888
  port: 8084
  
user:
  #url: http://Gateway-Service:8080/api/auth
  url: http://gateway-service:8090/api/auth
