spring:
  security:
    user:
      name: mabrouka
      password: annabi
  application:
      name: Email_Service
      
      
  #  Eureka configuration
eureka:
  instance:
    hostname: Email_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka




#  Server configuration
server:
  port: 8086

user:
  #url: http://Gateway-Service:8080/api/auth
  url: http://gateway-service:8090/api/auth
