spring:
  application:
    name: Ged_Service
    
  security:
    user:
      name: mabrouka
      password: annabi
  data:
    mongodb:
      database: admin
      username: insy2s
      password: insy2s
      host: mongo
      port: 27017
server:
  port: 8088
#  Eureka configuration

eureka:
  instance:
    hostname: Ged_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka

user:
  url: http://gateway-service:8090/api/auth
